name: self-hosted-matrix

on: [workflow_dispatch]

jobs:
  greeting:
    runs-on: [self-hosted,azure]
    strategy:
      max-parallel: 1
      matrix:
        random: ["a","b","c","d"]
    steps:
    - uses: actions/checkout@v2
    - name: Echo name
      run: echo Hello, World
